apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/assstra/simple-app-k8s-api:1.3
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PG_HOST
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PG_PORT
            - name: PG_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PG_NAME
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
