apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: db-clam
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /tmp/k8s-postgres-data
