apiVersion: v1
kind: Pod
metadata:
  name: evil-sidecar-pod
spec:
  containers:
  - name: legitimate-app  # Looks innocent
    image: nginx
    resources:
      limits:
        memory: "100Mi"
  - name: memory-bomber   # Malicious sidecar
    image: polinux/stress
    resources:
      requests:
        memory: "1Gi"     # Requests excessive memory
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "900M"]  # Allocates 900MB