apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
spec:
  containers:
  - name: stress
    image: polinux/stress
    resources:
      requests:
        memory: "10Gi"
      limits:
        memory: "10Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "9G", "--vm-hang", "1"]