apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app
  name: minimal-role-ci
rules:
# TODO: change this to be able to push simple-app
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]