apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app
  name: minimal-role-ci
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["create", "delete"]