apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment-1
  namespace: arc-systems
spec:
  replicas: 1
  template:
    spec:
      repository: noetarbouriech/k8s-clam