# apiVersion: cilium.io/v2
# kind: CiliumNetworkPolicy
# metadata:
#   name: default-deny-all
#   namespace: app-clam
# spec:
#   endpointSelector: {}
#   ingress:
#   - fromEndpoints:
#     - {}
#   egress:
#   - toEndpoints:
#     - {}
#   description: "Default deny all policy for the namespace"
# ---
# apiVersion: cilium.io/v2
# kind: CiliumNetworkPolicy
# metadata:
#   name: allow-specific-traffic
#   namespace: app-clam
# spec:
#   endpointSelector:
#     matchLabels:
#       app: your-app
#   ingress:
#   - fromEndpoints:
#     - matchLabels:
#         app: allowed-source-app
#     toPorts:
#     - ports:
#       - port: "80"
#       - port: "443"
#   egress:
#   - toEndpoints:
#     - matchLabels:
#         k8s:io.kubernetes.pod.namespace: kube-system
#         k8s-app: kube-dns
#     toPorts:
#     - ports:
#       - port: "53"
#       protocol: UDP
#   description: "Allow only specific traffic patterns"