name: Deploy Kubernetes YAMLs

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository name with owner. For example, actions/checkout"
        required: true
        default: "noetarbouriech/k8s-clam"
      folder:
        description: "Folder containing YAML files"
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository }}

      - uses: azure/setup-kubectl@v4

      - name: Apply YAMLs with kubectl
        run: |
          kubectl apply -f ${{ github.event.inputs.folder }} --recursive
